pipeline {
    agent {
        label "master"
    }
    stages {
       stage('envsetup') {
           steps {
              echo " mvn path setup "
              sh " M3_HOME=/home/vagrant/apache-maven-3.8.6 "
              sh " export PATH=$PATH:$M3_HOME/bin "
           }
       }    
       stage('Build') {
          steps {
              echo "building the code"
              sh 'mvn compile'
          }
       }
       stage('Test') {
          steps {
            echo "mvn test"
            
          }
       }
       stage('Deploy') {
          steps {
            echo "mvn install"
          }
       }
    }
}
