pipeline {
    agent {
        label "master"
    }
    tools {
        maven 'maven'
    }
    stages {
       stage('envsetup') {
           steps {
              echo " mvn path setup "
           }
       }    
       stage('Build') {
          steps {
              echo "building the code"
              sh "cd helloworld"
              sh 'mvn -f helloworld/pom.xml compile'
          }
       }
       stage('Test') {
          steps {
            echo "mvn -f helloworld/pom.xml test"
            
          }
       }
       stage('Deploy') {
          steps {
            echo "mvn -f helloworld/pom.xml install"
          }
       }
    }
}
